import type { Metadata, Viewport } from "next";
import { Figtree } from "next/font/google";
import { LocaleProvider } from "@/providers/locale";
import { RouteProvider } from "@/providers/router-provider";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";

const figtree = Figtree({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-figtree",
});

export const metadata: Metadata = {
    title: "Starter kit — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en-AU" suppressHydrationWarning>
            <body className={cx(figtree.variable, "bg-primary antialiased")}>
                <LocaleProvider locale="en-AU">
                    <RouteProvider>
                        <Theme>{children}</Theme>
                    </RouteProvider>
                </LocaleProvider>
            </body>
        </html>
    );
}
